apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: drone-api
  template:
    metadata:
      labels:
        app: drone-api
    spec:
      containers:
      - name: drone-api
        image: jeff/drone-api:latest
        ports:
        - containerPort: 5000

